gui:
  nerdFontsVersion: "3"
  showFileTrue: true
  tabWidth: 2
  sidePanelWidth: 0.2
  scrollPastBottom: false
  scrollOffMargin: 4
  expandFocusedSidePanel: true
  wrapLinesInStagingView: true
  commandLogSize: 15
  theme:
    activeBorderColor:
      - '#ffa500'
      - bold
  
git:
  diffContextSize: 5

